version: '3'
services:
  # current project
  web:
    # dockerfile is here and build from here
    image: btholt/node-app
    ports:
      - '3000:3000'
    links:
      # this container is linked to db
      # Since this is dependant on db, it starts db container first
      - db
    # kubernetes needs to know about the type of service
    labels:
      kompose.service.type: LoadBalancer
    environment:
      - MONGO_CONNECTION_STRING=mongodb://db:27017
  db:
    image: mongo:3
    ports:
      - '27017'
